name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - name: Install Bun
        run: npm install -g bun
      - name: Install dependencies
        run: bun install
      - name: Verify if runs
        run: |
          if bun run build; then
            echo "Project runs successfully"
          else
            echo "Project failed to run"
            exit 1
          fi
      - name: Release
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main
